name: Release Go Binary

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binaries
        run: |
          BINARY_NAME="myapp"
          VERSION=${GITHUB_REF#refs/tags/}
          
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o "${BINARY_NAME}-linux-amd64"
          tar czf "${BINARY_NAME}-linux-amd64.tar.gz" "${BINARY_NAME}-linux-amd64"
          
          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -o "${BINARY_NAME}-darwin-amd64"
          tar czf "${BINARY_NAME}-darwin-amd64.tar.gz" "${BINARY_NAME}-darwin-amd64"
          
          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -o "${BINARY_NAME}-windows-amd64.exe"
          zip "${BINARY_NAME}-windows-amd64.zip" "${BINARY_NAME}-windows-amd64.exe"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            myapp-linux-amd64.tar.gz
            myapp-darwin-amd64.tar.gz
            myapp-windows-amd64.zip
          draft: false
          prerelease: false
          generate_release_notes: true
